# Generated by Django 4.0.3 on 2022-03-29 18:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_profile_first_name_profile_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='date',
        ),
        migrations.AddField(
            model_name='visit',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
